import { useCallback, useEffect, useState } from "react";
import { corporateArApi, errorMessage } from "../../api";
import { useRealtime } from "../../hooks/useRealtime";
import { CorporateClient, CorporateInput, FileChanges } from "./types";
import { ImportedRow } from "./csvMapping";

export interface ImportSummary {
  added: number;
  updated: number;
  /** Rows that came without a key and received an automatic one. */
  generated: number;
}

/** Result of a save: the client is saved even when some documents could not be sent. */
export interface SaveResult {
  client: CorporateClient;
  /** Names of the documents that could not be uploaded / removed. */
  failedFiles: string[];
}

export function useCorporateClients() {
  const [clients, setClients] = useState<CorporateClient[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const reload = useCallback(async () => {
    try {
      setClients(await corporateArApi.list());
      setError(null);
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setLoaded(true);
    }
  }, []);

  useEffect(() => {
    void reload();
  }, [reload]);

  // Another agent added / changed / deleted something: refresh.
  useRealtime((m) => {
    if (m.event === "corporate_ar.changed") void reload();
  });

  /** Applies the document changes of the form to a saved client. */
  const applyFiles = useCallback(async (code: string, changes: FileChanges, names: Map<number, string>): Promise<string[]> => {
    const failed: string[] = [];
    for (const id of changes.removeIds) {
      try {
        await corporateArApi.deleteFile(code, id);
      } catch {
        failed.push(names.get(id) ?? `document ${id}`);
      }
    }
    for (const f of changes.add) {
      try {
        await corporateArApi.uploadFile(code, f);
      } catch (e) {
        failed.push(`${f.name} (${errorMessage(e)})`);
      }
    }
    return failed;
  }, []);

  /** Creates a client; its key is generated by the backend. */
  const create = useCallback(
    async (data: CorporateInput, changes: FileChanges): Promise<SaveResult> => {
      const created = await corporateArApi.create(data);
      const failedFiles = await applyFiles(created.code, changes, new Map());
      await reload();
      return { client: created, failedFiles };
    },
    [applyFiles, reload],
  );

  const update = useCallback(
    async (current: CorporateClient, data: CorporateInput, changes: FileChanges): Promise<SaveResult> => {
      const saved = await corporateArApi.update(current.code, data);
      const failedFiles = await applyFiles(current.code, changes, new Map(current.files.map((f) => [f.id, f.name])));
      await reload();
      return { client: saved, failedFiles };
    },
    [applyFiles, reload],
  );

  const remove = useCallback(
    async (code: string) => {
      await corporateArApi.remove(code);
      await reload();
    },
    [reload],
  );

  /**
   * Imports rows: each row without a key gets its own generated key; a row whose
   * key already exists updates that client (its attached invoices are kept).
   * All or nothing — done in one transaction by the backend.
   */
  const importRows = useCallback(
    async (rows: ImportedRow[]): Promise<ImportSummary> => {
      const result = await corporateArApi.importRows(rows);
      await reload();
      return result;
    },
    [reload],
  );

  return { clients, loaded, error, create, update, remove, importRows };
}

export type CorporateStore = ReturnType<typeof useCorporateClients>;
