--
-- PostgreSQL database dump
--

\restrict k8PthxU3lbyqnea30zHimvpiEVETloP4pexB9j0IWSlQrh7SnECytjeYeUj1Srq

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apres_gaia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia (
    n integer NOT NULL,
    codetat integer,
    codsit integer,
    cg integer,
    n_appel character varying(50),
    intitule character varying(255),
    adresse character varying(255),
    code_postal integer,
    type_de_compte integer,
    abonnement numeric(12,2),
    dus_ant numeric(12,2),
    montant_compteur numeric(12,2),
    nbre_ticket integer,
    ticket numeric(12,2),
    credit numeric(12,2),
    code_payeur integer,
    ccp bigint,
    date_vigueur_abt date,
    date_derniere_modif date,
    cod_cpt integer,
    nouvel_index integer,
    ancien_index integer,
    date_rnp date,
    dnpf date,
    repere character varying(100),
    actel character varying(255),
    n_client bigint,
    commune character varying(255),
    bat character varying(50),
    esc character varying(50),
    etage character varying(50),
    porte character varying(50),
    ccat integer,
    ndos integer,
    nvdi character varying(100),
    "motif res" character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.apres_gaia OWNER TO postgres;

--
-- Name: apres_gaia_med; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_med (
    id integer NOT NULL,
    n integer NOT NULL,
    invitation_paiement_date date,
    invitation_paiement_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    med_lettre_date date,
    med_lettre_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    engagement_date date,
    engagement_etat character varying(20) DEFAULT 'NON_ENGAGE'::character varying NOT NULL,
    cas_particulier character varying(100),
    cas_particulier_date date,
    cas_particulier_commentaire text,
    med_huissier_nom character varying(100),
    med_huissier_prenom character varying(100),
    med_huissier_date date,
    med_huissier_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    etat_juridique character varying(100) DEFAULT 'Procédure en cours'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_engagement_etat CHECK (((engagement_etat)::text = ANY ((ARRAY['ENGAGE'::character varying, 'NON_ENGAGE'::character varying])::text[]))),
    CONSTRAINT chk_etat_juridique CHECK (((etat_juridique)::text = ANY ((ARRAY['Procédure en cours'::character varying, 'Entreprise gagnante – première décision'::character varying, 'Client gagnant – première décision'::character varying, 'Entreprise gagnante – après recours'::character varying, 'Client gagnant – après recours'::character varying, 'Dossier clôturé'::character varying])::text[]))),
    CONSTRAINT chk_invitation_paiement_etat CHECK (((invitation_paiement_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[]))),
    CONSTRAINT chk_med_huissier_etat CHECK (((med_huissier_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[]))),
    CONSTRAINT chk_med_lettre_etat CHECK (((med_lettre_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[])))
);


ALTER TABLE public.apres_gaia_med OWNER TO postgres;

--
-- Name: apres_gaia_med_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_med ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_med_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_n_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_n_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_rappel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_rappel (
    id integer NOT NULL,
    n integer NOT NULL,
    type character varying(100) NOT NULL,
    reference_date date,
    reference_source character varying(255),
    echeance_date date,
    mois_impayes integer,
    jours_ecoules integer,
    solde_du numeric(12,2),
    message text,
    statut character varying(20) DEFAULT 'nouveau'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at timestamp with time zone,
    resolved_at timestamp with time zone
);


ALTER TABLE public.apres_gaia_rappel OWNER TO postgres;

--
-- Name: apres_gaia_rappel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_rappel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_rappel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_regelement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_regelement (
    ref integer NOT NULL,
    n integer NOT NULL,
    somme_versement numeric(12,2),
    date_versement date,
    lieu_versement character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    statut character varying(20) DEFAULT 'en_attente'::character varying NOT NULL,
    CONSTRAINT chk_apres_gaia_regelement_statut CHECK (((statut)::text = ANY ((ARRAY['en_attente'::character varying, 'valide'::character varying, 'refuse'::character varying])::text[])))
);


ALTER TABLE public.apres_gaia_regelement OWNER TO postgres;

--
-- Name: apres_gaia_regelement_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_regelement ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_regelement_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avant_gaia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avant_gaia (
    ref integer NOT NULL,
    actel character varying(255),
    n_abonne character varying(50),
    intitule character varying(255),
    adresse_01 character varying(255),
    adresse_02 character varying(255),
    dnpf integer,
    type_de_compte integer,
    abonnement numeric(12,2),
    "dus Anterieur" numeric(12,2),
    montant_compteur numeric(12,2),
    nombre_ticket integer,
    montant_ticket numeric(12,2),
    credit numeric(12,2),
    code_payeur integer,
    n_ccp bigint,
    somme_ht numeric(12,2),
    ttc numeric(12,2),
    tva numeric(12,2),
    nouveau_index integer,
    avoir numeric(12,2),
    n_bimestre integer,
    annee_bimestre integer,
    n_s_t integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.avant_gaia OWNER TO postgres;

--
-- Name: avant_gaia_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avant_gaia ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avant_gaia_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avant_gaia_versement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avant_gaia_versement (
    ref integer NOT NULL,
    actel character varying(255),
    n_abonne character varying(50),
    montant_versement numeric(12,2),
    n_bimestre integer,
    annee_bimestre integer,
    n_versement integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.avant_gaia_versement OWNER TO postgres;

--
-- Name: avant_gaia_versement_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avant_gaia_versement ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avant_gaia_versement_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: corporate_ar_client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corporate_ar_client (
    code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    creance numeric(14,2) DEFAULT 0 NOT NULL,
    numero_facture character varying(100),
    date_facture date,
    designation character varying(255) NOT NULL,
    observation character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_corporate_ar_creance CHECK ((creance >= (0)::numeric))
);


ALTER TABLE public.corporate_ar_client OWNER TO postgres;

--
-- Name: corporate_ar_counter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corporate_ar_counter (
    id smallint DEFAULT 1 NOT NULL,
    last_number integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_corporate_ar_counter_single CHECK ((id = 1))
);


ALTER TABLE public.corporate_ar_counter OWNER TO postgres;

--
-- Name: corporate_ar_file; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corporate_ar_file (
    id integer NOT NULL,
    client_code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    size integer NOT NULL,
    data bytea NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.corporate_ar_file OWNER TO postgres;

--
-- Name: corporate_ar_file_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.corporate_ar_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.corporate_ar_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: apres_gaia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia (n, codetat, codsit, cg, n_appel, intitule, adresse, code_postal, type_de_compte, abonnement, dus_ant, montant_compteur, nbre_ticket, ticket, credit, code_payeur, ccp, date_vigueur_abt, date_derniere_modif, cod_cpt, nouvel_index, ancien_index, date_rnp, dnpf, repere, actel, n_client, commune, bat, esc, etage, porte, ccat, ndos, nvdi, "motif res", created_at, updated_at) FROM stdin;
1	1	10	1	APP001	SARL ALPHA	12 Rue des Oliviers	16000	1	12500.00	1500.00	11000.00	2	500.00	300.00	1	123456789	2026-01-01	2026-02-15	1001	2500	2200	2026-02-01	2026-02-10	REP001	ACTEL ALGER	100001	Alger	B1	E2	3	12	1	5001	NVDI001	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
2	1	10	1	APP002	ETS BETA	25 Rue Didouche Mourad	16000	1	9800.00	1200.00	8600.00	1	250.00	150.00	2	234567890	2026-01-01	2026-02-20	1002	1800	1600	2026-02-05	2026-02-12	REP002	ACTEL ALGER	100002	Alger	B2	E1	2	8	1	5002	NVDI002	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
3	2	20	2	APP003	SARL GAMMA	8 Rue Larbi Ben M'hidi	19000	2	15750.00	2300.00	13450.00	3	750.00	400.00	1	345678901	2026-01-15	2026-02-18	1003	3200	2900	2026-02-10	2026-02-15	REP003	ACTEL SETIF	100003	Setif	C1	E3	4	15	2	5003	NVDI003	Modification	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
4	1	10	1	APP004	ETS DELTA	45 Rue de la Liberté	16000	1	7200.00	800.00	6400.00	1	200.00	100.00	2	456789012	2026-01-01	2026-02-22	1004	1400	1200	2026-02-12	2026-02-18	REP004	ACTEL ALGER	100004	Alger	D1	E2	1	4	1	5004	NVDI004	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
5	2	20	2	APP005	SARL EPSILON	17 Rue de Constantine	25000	2	11200.00	1800.00	9400.00	2	450.00	250.00	1	567890123	2026-01-10	2026-02-25	1005	2100	1900	2026-02-15	2026-02-20	REP005	ACTEL CONSTANTINE	100005	Constantine	E1	E1	3	10	2	5005	NVDI005	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
6	1	10	1	APP006	SARL TEST API	15 Rue des Freres Bouadou	16000	1	10500.50	1200.00	9300.50	2	450.00	200.00	1	678901234	2026-09-01	2026-09-28	1006	3500	3200	2026-09-15	2026-09-20	REP006	ACTEL ALGER	100006	Alger	F1	E2	4	16	1	5006	NVDI006	Normal	2026-09-28 00:27:32.514166+00	2026-09-28 00:27:32.514166+00
7	1	10	201	APP007	SARL OMEGA	12 Rue Didouche Mourad	16000	1	7200.00	1500.00	6300.00	2	120.00	500.00	101	100007	2024-01-15	2026-03-05	1	18450	17820	2026-03-01	2026-03-02	REP007	ACTEL ALGER	100007	Alger	B	2	3	12	1	3007	NV007	Retard de paiement	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
8	1	11	202	APP008	ETS HORIZON	45 Rue de la Liberté	19000	2	5800.00	2300.00	4200.00	1	80.00	300.00	102	100008	2023-06-10	2026-03-06	2	15320	14900	2026-03-02	2026-03-03	REP008	ACTEL SETIF	100008	Sétif	A	1	2	08	2	3008	NV008	Normal	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
9	2	12	203	APP009	SARL EL DJAZAIR	8 Rue des Frères	50000	1	6400.00	3100.00	5100.00	3	150.00	200.00	103	100009	2022-09-20	2026-03-07	1	16780	16000	2026-03-03	2026-03-04	REP009	ACTEL BATNA	100009	Batna	C	3	1	05	1	3009	NV009	Décès	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
10	1	13	204	APP010	ETS ALPHA SERVICES	21 Boulevard Emir Abdelkader	31000	2	8100.00	900.00	7300.00	2	100.00	400.00	104	100010	2021-11-05	2026-03-08	2	22100	21450	2026-03-04	2026-03-05	REP010	ACTEL ORAN	100010	Oran	D	2	4	18	2	3010	NV010	Insolvabilité	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
11	1	14	205	APP011	SARL EL BAHJA	17 Rue Larbi Ben M'Hidi	25000	1	6900.00	1800.00	5400.00	1	70.00	250.00	105	100011	2023-02-14	2026-03-09	1	19340	18700	2026-03-05	2026-03-06	REP011	ACTEL CONSTANTINE	100011	Constantine	A	4	2	11	1	3011	NV011	Contestation	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
12	2	15	206	APP012	ETS NASSIM	33 Rue Ahmed Zabana	30000	2	4500.00	2700.00	3900.00	2	90.00	150.00	106	100012	2020-08-22	2026-03-10	2	14200	13600	2026-03-06	2026-03-07	REP012	ACTEL OUARGLA	100012	Ouargla	B	1	5	22	2	3012	NV012	Succession	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
13	1	16	207	APP013	SARL EL AMAL	5 Avenue de l'ALN	13000	1	7600.00	1200.00	6800.00	1	60.00	350.00	107	100013	2024-03-18	2026-03-11	1	17890	17200	2026-03-07	2026-03-08	REP013	ACTEL TLEMCEN	100013	Tlemcen	C	2	3	09	1	3013	NV013	Normal	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
14	1	17	208	APP014	ETS MODERNE	28 Rue Larbi Tebessi	9000	2	5300.00	1900.00	4700.00	2	110.00	100.00	108	100014	2022-12-01	2026-03-12	2	16050	15500	2026-03-08	2026-03-09	REP014	ACTEL BLIDA	100014	Blida	A	3	2	14	2	3014	NV014	Modification	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
15	2	18	209	APP015	SARL EL WIFAK	14 Rue de la Paix	21000	1	6200.00	2500.00	5800.00	3	130.00	300.00	109	100015	2021-05-16	2026-03-13	1	18900	18100	2026-03-09	2026-03-10	REP015	ACTEL SKIKDA	100015	Skikda	D	2	1	06	1	3015	NV015	Retard de paiement	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
16	1	19	210	APP016	ETS EL FATEH	9 Rue Mohamed Boudiaf	23000	2	7100.00	1600.00	6100.00	1	50.00	450.00	110	100016	2023-07-08	2026-03-14	2	20200	19500	2026-03-10	2026-03-11	REP016	ACTEL ANNABA	100016	Annaba	B	4	3	16	2	3016	NV016	Normal	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
17	1	20	211	APP017	SARL ITHRI	31 Rue des Oliviers	15000	1	6800.00	2900.00	5200.00	2	95.00	200.00	111	100017	2022-01-25	2026-03-15	1	17100	16500	2026-03-11	2026-03-12	REP017	ACTEL TIZI OUZOU	100017	Tizi Ouzou	C	1	4	20	1	3017	NV017	Insolvabilité	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
18	2	21	212	APP018	ETS EL MANAR	19 Rue des Martyrs	16000	2	4900.00	2100.00	4300.00	1	75.00	120.00	112	100018	2020-04-11	2026-03-16	2	13500	12900	2026-03-12	2026-03-13	REP018	ACTEL ALGER	100018	Alger	A	2	2	10	2	3018	NV018	Décès	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
19	1	22	213	APP019	SARL ESSOR	42 Avenue de l'Indépendance	19000	1	8400.00	1400.00	7600.00	2	125.00	500.00	113	100019	2024-01-30	2026-03-17	1	21400	20700	2026-03-13	2026-03-14	REP019	ACTEL SETIF	100019	Sétif	D	3	5	25	1	3019	NV019	Contestation	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
20	1	23	214	APP020	ETS EL BARAKA	7 Rue de la République	50000	2	5700.00	2200.00	4800.00	1	85.00	180.00	114	100020	2021-09-09	2026-03-18	2	14900	14300	2026-03-14	2026-03-15	REP020	ACTEL BATNA	100020	Batna	B	1	3	07	2	3020	NV020	Succession	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
21	2	24	215	APP021	SARL RAHMA	16 Rue des Frères Bouadou	31000	1	7300.00	1700.00	6400.00	2	100.00	250.00	115	100021	2023-05-12	2026-03-19	1	18100	17500	2026-03-15	2026-03-16	REP021	ACTEL ORAN	100021	Oran	C	4	2	13	1	3021	NV021	Retard de paiement	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
22	1	25	216	APP022	ETS EL HANA	23 Rue de la Gare	25000	2	6100.00	2600.00	5100.00	3	140.00	220.00	116	100022	2022-10-18	2026-03-20	2	16500	15800	2026-03-16	2026-03-17	REP022	ACTEL CONSTANTINE	100022	Constantine	A	2	4	19	2	3022	NV022	Modification	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
23	1	26	217	APP023	SARL EL KARAMA	11 Boulevard de l'ALN	30000	1	7900.00	1300.00	6900.00	1	65.00	400.00	117	100023	2024-02-05	2026-03-21	1	19800	19100	2026-03-17	2026-03-18	REP023	ACTEL OUARGLA	100023	Ouargla	D	3	1	04	1	3023	NV023	Normal	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
24	2	27	218	APP024	ETS EL YASMINE	38 Rue de la Victoire	9000	2	5200.00	2800.00	4500.00	2	90.00	150.00	118	100024	2020-06-27	2026-03-22	2	15100	14500	2026-03-18	2026-03-19	REP024	ACTEL BLIDA	100024	Blida	B	4	3	15	2	3024	NV024	Insolvabilité	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
25	1	28	219	APP025	SARL EL FETH	6 Rue des Aurès	21000	1	6700.00	2000.00	5700.00	1	80.00	300.00	119	100025	2021-12-15	2026-03-23	1	17600	16900	2026-03-19	2026-03-20	REP025	ACTEL SKIKDA	100025	Skikda	C	2	5	21	1	3025	NV025	Contestation	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
26	1	29	220	APP026	ETS EL DJOUD	27 Rue de la Paix	23000	2	6000.00	2400.00	5000.00	2	105.00	200.00	120	100026	2023-03-22	2026-03-24	2	15800	15200	2026-03-20	2026-03-21	REP026	ACTEL ANNABA	100026	Annaba	A	1	2	09	2	3026	NV026	Succession	2026-09-30 11:56:56.818251+00	2026-09-30 11:56:56.818251+00
\.


--
-- Data for Name: apres_gaia_med; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia_med (id, n, invitation_paiement_date, invitation_paiement_etat, med_lettre_date, med_lettre_etat, engagement_date, engagement_etat, cas_particulier, cas_particulier_date, cas_particulier_commentaire, med_huissier_nom, med_huissier_prenom, med_huissier_date, med_huissier_etat, etat_juridique, created_at, updated_at) FROM stdin;
3	3	2026-01-25	ENVOYEE	2026-02-10	ENVOYEE	2026-09-29	ENGAGE	Insolvabilité	2026-03-05	Situation financière particulière du client.	kali	meriem	2026-09-29	ENVOYEE	Procédure en cours	2026-09-29 00:22:05.688827+00	2026-09-29 10:46:51.821634+00
5	5	2026-09-29	ENVOYEE	2026-09-29	ENVOYEE	2026-09-29	ENGAGE	\N	\N	\N	\N	\N	\N	NON_ENVOYEE	Procédure en cours	2026-09-29 10:51:49.450705+00	2026-09-29 10:51:52.995832+00
1	1	2026-01-15	ENVOYEE	2026-02-10	ENVOYEE	2026-02-20	ENGAGE	\N	\N	\N	\N	\N	2026-09-30	ENVOYEE	Procédure en cours	2026-09-29 00:22:05.688827+00	2026-09-30 11:43:06.50962+00
6	9	2026-09-30	ENVOYEE	2026-09-30	ENVOYEE	2026-09-30	ENGAGE	\N	\N	\N	\N	\N	\N	NON_ENVOYEE	Procédure en cours	2026-09-30 13:56:31.999684+00	2026-09-30 13:58:32.266402+00
4	4	2026-02-01	ENVOYEE	2026-02-20	ENVOYEE	2026-03-01	ENGAGE	Contestation	2026-03-10	Le client conteste le montant réclamé.	Kaci	Mohamed	2026-03-20	ENVOYEE	Entreprise gagnante – première décision	2026-09-29 00:22:05.688827+00	2026-09-30 15:22:05.556356+00
7	7	2026-09-30	ENVOYEE	2026-09-30	ENVOYEE	2026-09-30	ENGAGE	\N	\N	\N	Kali	meriem	2026-09-30	ENVOYEE	Procédure en cours	2026-09-30 15:16:57.90184+00	2026-09-30 15:22:30.089445+00
2	2	2026-01-20	ENVOYEE	2026-02-15	ENVOYEE	2026-02-20	ENGAGE	malade	2026-09-30	acoord	Benali	Ahmed	2026-03-15	ENVOYEE	Client gagnant – première décision	2026-09-29 00:22:05.688827+00	2026-10-01 00:42:16.211212+00
\.


--
-- Data for Name: apres_gaia_rappel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia_rappel (id, n, type, reference_date, reference_source, echeance_date, mois_impayes, jours_ecoules, solde_du, message, statut, created_at, read_at, resolved_at) FROM stdin;
2	2	versement_mensuel	2026-02-20	engagement	2026-09-18	7	222	19600.00	Rappel : le client n° 2 (ETS BETA) est engagé mais n'a effectué aucun versement depuis son engagement du 20/02/2026 — 222 jours écoulés (7 mois). Solde dû : 19600.00.	resolu	2026-09-30 12:03:27.968728+00	2026-09-30 12:09:47.073081+00	2026-09-30 12:18:57.580963+00
1	4	versement_mensuel	2026-03-01	engagement	2026-09-27	7	214	14400.00	Rappel : le client n° 4 (ETS DELTA) est engagé mais n'a effectué aucun versement depuis son engagement du 01/03/2026 — 212 jours écoulés (7 mois). Solde dû : 11900.00.	lu	2026-09-29 10:42:51.254709+00	2026-09-30 15:21:29.299758+00	\N
\.


--
-- Data for Name: apres_gaia_regelement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia_regelement (ref, n, somme_versement, date_versement, lieu_versement, created_at, updated_at, statut) FROM stdin;
1	1	3000.00	2026-02-05	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
2	1	2500.00	2026-02-20	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
3	1	1500.00	2026-03-10	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	en_attente
6	3	5000.00	2026-02-15	Bureau ACTEL Setif	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
9	5	3500.00	2026-02-22	Bureau ACTEL Constantine	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	en_attente
10	5	2000.00	2026-03-15	Bureau ACTEL Constantine	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
12	1	2000.00	\N	alger	2026-09-28 09:57:47.661986+00	2026-09-28 09:57:47.661986+00	valide
14	1	3000.00	\N	kouba	2026-09-28 12:19:17.279334+00	2026-09-28 12:19:17.279334+00	refuse
15	1	4000.00	\N	koubq	2026-09-28 12:20:01.272027+00	2026-09-28 12:20:01.272027+00	valide
17	2	3000.00	\N	kouba	2026-09-30 12:18:57.555155+00	2026-09-30 12:18:57.555155+00	valide
\.


--
-- Data for Name: avant_gaia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.avant_gaia (ref, actel, n_abonne, intitule, adresse_01, adresse_02, dnpf, type_de_compte, abonnement, "dus Anterieur", montant_compteur, nombre_ticket, montant_ticket, credit, code_payeur, n_ccp, somme_ht, ttc, tva, nouveau_index, avoir, n_bimestre, annee_bimestre, n_s_t, created_at, updated_at) FROM stdin;
1	ACTEL ALGER	100001	SARL ALPHA	12 Rue des Oliviers	Alger Centre	1	1	12500.00	1500.00	11000.00	2	500.00	300.00	1	123456789	10000.00	11900.00	1900.00	2500	0.00	1	2026	1001	2026-09-28 00:10:34.285008+00	2026-09-28 00:10:34.285008+00
2	ACTEL ALGER	100002	ETS BETA	25 Rue Didouche Mourad	Alger Centre	1	1	9800.00	1200.00	8600.00	1	250.00	150.00	2	234567890	8000.00	9440.00	1440.00	1800	0.00	1	2026	1002	2026-09-28 00:10:34.285008+00	2026-09-28 00:10:34.285008+00
3	ACTEL SETIF	100003	SARL GAMMA	8 Rue Larbi Ben M'hidi	Setif Centre	2	2	15750.00	2300.00	13450.00	3	750.00	400.00	1	345678901	13000.00	15340.00	2340.00	3200	0.00	1	2026	1003	2026-09-28 00:10:34.285008+00	2026-09-28 00:10:34.285008+00
\.


--
-- Data for Name: avant_gaia_versement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.avant_gaia_versement (ref, actel, n_abonne, montant_versement, n_bimestre, annee_bimestre, n_versement, created_at, updated_at) FROM stdin;
1	ACTEL ALGER	100001	3000.00	1	2026	1	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
2	ACTEL ALGER	100001	2500.00	1	2026	2	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
3	ACTEL ALGER	100002	4000.00	1	2026	1	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
4	ACTEL SETIF	100003	5000.00	1	2026	1	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
\.


--
-- Data for Name: corporate_ar_client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.corporate_ar_client (code, name, creance, numero_facture, date_facture, designation, observation, created_at, updated_at) FROM stdin;
CAR-000001	SARL El Amel Construction	1250000.00	FAC-2026-00125	2026-01-15	Facture impayée	Relance envoyée au client.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000002	EURL Techno Solutions	485000.50	FAC-2026-00218	2026-02-03	Retard de paiement	Client contacté par téléphone.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000003	SARL Atlas Distribution	875300.00	FAC-2026-00341	2026-02-18	Facture impayée	Paiement attendu prochainement.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000004	SPA Horizon Industries	2345000.75	FAC-2026-00402	2026-03-01	Retard de paiement	Dossier transmis au service recouvrement.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000005	SARL Biskra Services	320750.00	FAC-2026-00489	2026-03-12	Échéance dépassée	Promesse de paiement reçue.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000006	EURL Sahara Logistics	965400.25	FAC-2026-00517	2026-03-25	Facture impayée	Deuxième relance envoyée.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000007	SARL Maghreb Engineering	1789000.00	FAC-2026-00603	2026-04-07	Retard de paiement	Client demande un délai supplémentaire.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000008	SPA Algérie Maintenance	642800.00	FAC-2026-00678	2026-04-19	Échéance dépassée	Aucun retour après relance.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000009	SARL Oasis Informatique	215600.00	FAC-2026-00724	2026-05-02	Facture impayée	Relance par email effectuée.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
CAR-000010	EURL North Africa Trading	1543200.90	FAC-2026-00811	2026-05-16	Retard de paiement	Dossier en cours de traitement.	2026-10-01 01:27:51.112671+00	2026-10-01 01:27:51.112671+00
\.


--
-- Data for Name: corporate_ar_counter; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.corporate_ar_counter (id, last_number) FROM stdin;
1	10
\.


--
-- Data for Name: corporate_ar_file; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.corporate_ar_file (id, client_code, name, content_type, size, data, created_at) FROM stdin;
\.


--
-- Name: apres_gaia_med_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_med_id_seq', 7, true);


--
-- Name: apres_gaia_n_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_n_seq', 26, true);


--
-- Name: apres_gaia_rappel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_rappel_id_seq', 2, true);


--
-- Name: apres_gaia_regelement_ref_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_regelement_ref_seq', 19, true);


--
-- Name: avant_gaia_ref_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.avant_gaia_ref_seq', 3, true);


--
-- Name: avant_gaia_versement_ref_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.avant_gaia_versement_ref_seq', 4, true);


--
-- Name: corporate_ar_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.corporate_ar_file_id_seq', 1, false);


--
-- Name: apres_gaia_med apres_gaia_med_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_med
    ADD CONSTRAINT apres_gaia_med_pkey PRIMARY KEY (id);


--
-- Name: apres_gaia apres_gaia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia
    ADD CONSTRAINT apres_gaia_pkey PRIMARY KEY (n);


--
-- Name: apres_gaia_rappel apres_gaia_rappel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_rappel
    ADD CONSTRAINT apres_gaia_rappel_pkey PRIMARY KEY (id);


--
-- Name: apres_gaia_regelement apres_gaia_regelement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_regelement
    ADD CONSTRAINT apres_gaia_regelement_pkey PRIMARY KEY (ref);


--
-- Name: avant_gaia avant_gaia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avant_gaia
    ADD CONSTRAINT avant_gaia_pkey PRIMARY KEY (ref);


--
-- Name: avant_gaia_versement avant_gaia_versement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avant_gaia_versement
    ADD CONSTRAINT avant_gaia_versement_pkey PRIMARY KEY (ref);


--
-- Name: corporate_ar_client corporate_ar_client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_client
    ADD CONSTRAINT corporate_ar_client_pkey PRIMARY KEY (code);


--
-- Name: corporate_ar_counter corporate_ar_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_counter
    ADD CONSTRAINT corporate_ar_counter_pkey PRIMARY KEY (id);


--
-- Name: corporate_ar_file corporate_ar_file_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_file
    ADD CONSTRAINT corporate_ar_file_pkey PRIMARY KEY (id);


--
-- Name: idx_apres_gaia_med_n; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_med_n ON public.apres_gaia_med USING btree (n);


--
-- Name: idx_apres_gaia_rappel_n; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_rappel_n ON public.apres_gaia_rappel USING btree (n);


--
-- Name: idx_apres_gaia_rappel_statut; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_rappel_statut ON public.apres_gaia_rappel USING btree (statut);


--
-- Name: idx_apres_gaia_regelement_n; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_regelement_n ON public.apres_gaia_regelement USING btree (n);


--
-- Name: apres_gaia_rappel apres_gaia_rappel_n_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_rappel
    ADD CONSTRAINT apres_gaia_rappel_n_fkey FOREIGN KEY (n) REFERENCES public.apres_gaia(n) ON DELETE CASCADE;


--
-- Name: apres_gaia_med fk_apres_gaia_med_n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_med
    ADD CONSTRAINT fk_apres_gaia_med_n FOREIGN KEY (n) REFERENCES public.apres_gaia(n) ON DELETE CASCADE;


--
-- Name: corporate_ar_file fk_corporate_ar_file_client; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_file
    ADD CONSTRAINT fk_corporate_ar_file_client FOREIGN KEY (client_code) REFERENCES public.corporate_ar_client(code) ON DELETE CASCADE;


--
-- Name: apres_gaia_regelement fk_regelement_apres_gaia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_regelement
    ADD CONSTRAINT fk_regelement_apres_gaia FOREIGN KEY (n) REFERENCES public.apres_gaia(n);


--
-- PostgreSQL database dump complete
--

\unrestrict k8PthxU3lbyqnea30zHimvpiEVETloP4pexB9j0IWSlQrh7SnECytjeYeUj1Srq

