--
-- PostgreSQL database dump
--

\restrict 6iUCHWhvmccr7ZKlNKVQ43DGq2TZhcH6ZH4w7pRnwffjOyB06qZMQMNM8jnZN45

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apres_gaia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia (
    n integer NOT NULL,
    codetat integer,
    codsit integer,
    cg integer,
    n_appel character varying(50),
    intitule character varying(255),
    adresse character varying(255),
    code_postal integer,
    type_de_compte integer,
    abonnement numeric(12,2),
    dus_ant numeric(12,2),
    montant_compteur numeric(12,2),
    nbre_ticket integer,
    ticket numeric(12,2),
    credit numeric(12,2),
    code_payeur integer,
    ccp bigint,
    date_vigueur_abt date,
    date_derniere_modif date,
    cod_cpt integer,
    nouvel_index integer,
    ancien_index integer,
    date_rnp date,
    dnpf date,
    repere character varying(100),
    actel character varying(255),
    n_client bigint,
    commune character varying(255),
    bat character varying(50),
    esc character varying(50),
    etage character varying(50),
    porte character varying(50),
    ccat integer,
    ndos integer,
    nvdi character varying(100),
    "motif res" character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.apres_gaia OWNER TO postgres;

--
-- Name: apres_gaia_med; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_med (
    id integer NOT NULL,
    n integer NOT NULL,
    invitation_paiement_date date,
    invitation_paiement_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    med_lettre_date date,
    med_lettre_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    engagement_date date,
    engagement_etat character varying(20) DEFAULT 'NON_ENGAGE'::character varying NOT NULL,
    cas_particulier character varying(100),
    cas_particulier_date date,
    cas_particulier_commentaire text,
    med_huissier_nom character varying(100),
    med_huissier_prenom character varying(100),
    med_huissier_date date,
    med_huissier_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    etat_juridique character varying(100) DEFAULT 'Procédure en cours'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_engagement_etat CHECK (((engagement_etat)::text = ANY ((ARRAY['ENGAGE'::character varying, 'NON_ENGAGE'::character varying])::text[]))),
    CONSTRAINT chk_etat_juridique CHECK (((etat_juridique)::text = ANY ((ARRAY['Procédure en cours'::character varying, 'Entreprise gagnante – première décision'::character varying, 'Client gagnant – première décision'::character varying, 'Entreprise gagnante – après recours'::character varying, 'Client gagnant – après recours'::character varying, 'Dossier clôturé'::character varying])::text[]))),
    CONSTRAINT chk_invitation_paiement_etat CHECK (((invitation_paiement_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[]))),
    CONSTRAINT chk_med_huissier_etat CHECK (((med_huissier_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[]))),
    CONSTRAINT chk_med_lettre_etat CHECK (((med_lettre_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[])))
);


ALTER TABLE public.apres_gaia_med OWNER TO postgres;

--
-- Name: apres_gaia_med_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_med ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_med_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_n_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_n_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_rappel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_rappel (
    id integer NOT NULL,
    n integer NOT NULL,
    type character varying(100) NOT NULL,
    reference_date date,
    reference_source character varying(255),
    echeance_date date,
    mois_impayes integer,
    jours_ecoules integer,
    solde_du numeric(12,2),
    message text,
    statut character varying(20) DEFAULT 'nouveau'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at timestamp with time zone,
    resolved_at timestamp with time zone
);


ALTER TABLE public.apres_gaia_rappel OWNER TO postgres;

--
-- Name: apres_gaia_rappel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_rappel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_rappel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_regelement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_regelement (
    ref integer NOT NULL,
    n integer NOT NULL,
    somme_versement numeric(12,2),
    date_versement date,
    lieu_versement character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    statut character varying(20) DEFAULT 'en_attente'::character varying NOT NULL,
    CONSTRAINT chk_apres_gaia_regelement_statut CHECK (((statut)::text = ANY ((ARRAY['en_attente'::character varying, 'valide'::character varying, 'refuse'::character varying])::text[])))
);


ALTER TABLE public.apres_gaia_regelement OWNER TO postgres;

--
-- Name: apres_gaia_regelement_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_regelement ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_regelement_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avant_gaia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avant_gaia (
    ref integer NOT NULL,
    actel character varying(255),
    n_abonne character varying(50),
    intitule character varying(255),
    adresse_01 character varying(255),
    adresse_02 character varying(255),
    dnpf integer,
    type_de_compte integer,
    abonnement numeric(12,2),
    "dus Anterieur" numeric(12,2),
    montant_compteur numeric(12,2),
    nombre_ticket integer,
    montant_ticket numeric(12,2),
    credit numeric(12,2),
    code_payeur integer,
    n_ccp bigint,
    somme_ht numeric(12,2),
    ttc numeric(12,2),
    tva numeric(12,2),
    nouveau_index integer,
    avoir numeric(12,2),
    n_bimestre integer,
    annee_bimestre integer,
    n_s_t integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.avant_gaia OWNER TO postgres;

--
-- Name: avant_gaia_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avant_gaia ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avant_gaia_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avant_gaia_versement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avant_gaia_versement (
    ref integer NOT NULL,
    actel character varying(255),
    n_abonne character varying(50),
    montant_versement numeric(12,2),
    n_bimestre integer,
    annee_bimestre integer,
    n_versement integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.avant_gaia_versement OWNER TO postgres;

--
-- Name: avant_gaia_versement_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avant_gaia_versement ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avant_gaia_versement_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: corporate_ar_client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corporate_ar_client (
    code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    creance numeric(14,2) DEFAULT 0 NOT NULL,
    numero_facture character varying(100),
    date_facture date,
    designation character varying(255) NOT NULL,
    observation character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_corporate_ar_creance CHECK ((creance >= (0)::numeric))
);


ALTER TABLE public.corporate_ar_client OWNER TO postgres;

--
-- Name: corporate_ar_counter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corporate_ar_counter (
    id smallint DEFAULT 1 NOT NULL,
    last_number integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_corporate_ar_counter_single CHECK ((id = 1))
);


ALTER TABLE public.corporate_ar_counter OWNER TO postgres;

--
-- Name: corporate_ar_file; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.corporate_ar_file (
    id integer NOT NULL,
    client_code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    size integer NOT NULL,
    data bytea NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.corporate_ar_file OWNER TO postgres;

--
-- Name: corporate_ar_file_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.corporate_ar_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.corporate_ar_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_med apres_gaia_med_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_med
    ADD CONSTRAINT apres_gaia_med_pkey PRIMARY KEY (id);


--
-- Name: apres_gaia apres_gaia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia
    ADD CONSTRAINT apres_gaia_pkey PRIMARY KEY (n);


--
-- Name: apres_gaia_rappel apres_gaia_rappel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_rappel
    ADD CONSTRAINT apres_gaia_rappel_pkey PRIMARY KEY (id);


--
-- Name: apres_gaia_regelement apres_gaia_regelement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_regelement
    ADD CONSTRAINT apres_gaia_regelement_pkey PRIMARY KEY (ref);


--
-- Name: avant_gaia avant_gaia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avant_gaia
    ADD CONSTRAINT avant_gaia_pkey PRIMARY KEY (ref);


--
-- Name: avant_gaia_versement avant_gaia_versement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avant_gaia_versement
    ADD CONSTRAINT avant_gaia_versement_pkey PRIMARY KEY (ref);


--
-- Name: corporate_ar_client corporate_ar_client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_client
    ADD CONSTRAINT corporate_ar_client_pkey PRIMARY KEY (code);


--
-- Name: corporate_ar_counter corporate_ar_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_counter
    ADD CONSTRAINT corporate_ar_counter_pkey PRIMARY KEY (id);


--
-- Name: corporate_ar_file corporate_ar_file_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_file
    ADD CONSTRAINT corporate_ar_file_pkey PRIMARY KEY (id);


--
-- Name: idx_apres_gaia_med_n; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_med_n ON public.apres_gaia_med USING btree (n);


--
-- Name: idx_apres_gaia_rappel_n; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_rappel_n ON public.apres_gaia_rappel USING btree (n);


--
-- Name: idx_apres_gaia_rappel_statut; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_rappel_statut ON public.apres_gaia_rappel USING btree (statut);


--
-- Name: idx_apres_gaia_regelement_n; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_apres_gaia_regelement_n ON public.apres_gaia_regelement USING btree (n);


--
-- Name: apres_gaia_rappel apres_gaia_rappel_n_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_rappel
    ADD CONSTRAINT apres_gaia_rappel_n_fkey FOREIGN KEY (n) REFERENCES public.apres_gaia(n) ON DELETE CASCADE;


--
-- Name: apres_gaia_med fk_apres_gaia_med_n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_med
    ADD CONSTRAINT fk_apres_gaia_med_n FOREIGN KEY (n) REFERENCES public.apres_gaia(n) ON DELETE CASCADE;


--
-- Name: corporate_ar_file fk_corporate_ar_file_client; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.corporate_ar_file
    ADD CONSTRAINT fk_corporate_ar_file_client FOREIGN KEY (client_code) REFERENCES public.corporate_ar_client(code) ON DELETE CASCADE;


--
-- Name: apres_gaia_regelement fk_regelement_apres_gaia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_regelement
    ADD CONSTRAINT fk_regelement_apres_gaia FOREIGN KEY (n) REFERENCES public.apres_gaia(n);


--
-- PostgreSQL database dump complete
--

\unrestrict 6iUCHWhvmccr7ZKlNKVQ43DGq2TZhcH6ZH4w7pRnwffjOyB06qZMQMNM8jnZN45

