-- ============================================================
-- TABLE 6: apres_gaia_regelement
-- ============================================================
-- One change from what you pasted, per your own clarification:
--
--   Your original DDL declared "N" as THIS table's own identity primary
--   key. But you said N should be a foreign key pointing back at
--   apres_gaia.n, so a règlement row can be tied to the client it was
--   paid against.
--
--   Those two can't be the same column. `n` needs to repeat every time
--   the SAME client pays again (a client can pay several times — see the
--   "VERSEMENTS" history in your mockup) — but a primary key must be
--   unique per row. If N stayed the PK, a client could only ever have
--   ONE règlement, total.
--
--   Fix: this table gets its own identity PK — `ref`, same pattern as
--   avant_gaia_versement.ref — and `n` becomes a plain (non-unique)
--   foreign key column to apres_gaia(n). Insert a règlement by sending
--   `n` = the client's apres_gaia.n; that's what links a payment to a
--   client (see POST /api/apres-gaia/{n}/reglements).
--
-- Also, unlike an earlier version of this file: no `agent` column. Your
-- real DDL doesn't have one, and you asked me to stop inventing columns
-- that don't exist in your schema — dropped.
-- ============================================================

CREATE TABLE IF NOT EXISTS apres_gaia_regelement (
    ref INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    n INTEGER NOT NULL REFERENCES apres_gaia(n) ON DELETE CASCADE,

    somme_versement NUMERIC(12, 2),
    date_versement DATE,
    lieu_versement VARCHAR(255),

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_apres_gaia_regelement_n ON apres_gaia_regelement (n);
