-- ============================================================
-- TABLE 8: apres_gaia_rappel
-- Rappels (notifications) de versement pour les clients ENGAGÉS
-- (apres_gaia_med.engagement_etat = 'ENGAGE') qui n'ont rien versé
-- depuis un mois (30 jours par défaut, voir REMINDER_DELAY_DAYS).
--
-- NOUVELLE table — aucune table existante n'est modifiée.
-- Idempotent : CREATE ... IF NOT EXISTS, un re-run ne perd rien.
--
--   reference_date   : point de départ du décompte = la plus récente entre
--                      la date d'engagement et la date du dernier versement.
--   reference_source : 'engagement' ou 'versement' (d'où vient reference_date).
--   echeance_date    : reference_date + k × délai — l'échéance manquée qui a
--                      déclenché CE rappel (k = mois_impayes).
--   UNIQUE (n, type, echeance_date) : un même rappel n'est jamais créé deux fois,
--                      même si le contrôle tourne plusieurs fois par jour.
-- ============================================================

CREATE TABLE IF NOT EXISTS apres_gaia_rappel (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    n INTEGER NOT NULL REFERENCES apres_gaia(n) ON DELETE CASCADE,

    type VARCHAR(50) NOT NULL DEFAULT 'versement_mensuel',

    reference_date DATE NOT NULL,
    reference_source VARCHAR(20) NOT NULL,
    echeance_date DATE NOT NULL,
    mois_impayes INTEGER NOT NULL DEFAULT 1,
    jours_ecoules INTEGER NOT NULL,

    solde_du NUMERIC(12, 2),
    message TEXT NOT NULL,

    statut VARCHAR(20) NOT NULL DEFAULT 'nouveau',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,

    CONSTRAINT chk_apres_gaia_rappel_statut
        CHECK (statut IN ('nouveau', 'lu', 'resolu')),

    CONSTRAINT chk_apres_gaia_rappel_source
        CHECK (reference_source IN ('engagement', 'versement')),

    CONSTRAINT uq_apres_gaia_rappel UNIQUE (n, type, echeance_date)
);

CREATE INDEX IF NOT EXISTS idx_apres_gaia_rappel_n ON apres_gaia_rappel (n);
CREATE INDEX IF NOT EXISTS idx_apres_gaia_rappel_statut ON apres_gaia_rappel (statut);
