-- ============================================================
-- Corporate AR (entreprises) : clients, factures jointes, compteur de codes.
--
-- Avant, ces données vivaient dans IndexedDB (navigateur) : elles n'étaient
-- ni partagées entre agents, ni sauvegardées. Elles sont maintenant dans
-- PostgreSQL comme le reste du projet.
--
-- NOUVELLES tables — aucune table existante n'est modifiée.
-- Idempotent : CREATE ... IF NOT EXISTS, un re-run ne perd rien.
-- ============================================================

-- Un client = une entreprise. `code` est la clé primaire : CAR-000001, CAR-000002…
-- (générée par l'API ; un import CSV peut aussi apporter son propre code).
CREATE TABLE IF NOT EXISTS corporate_ar_client (
    code VARCHAR(50) PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    creance NUMERIC(14, 2) NOT NULL DEFAULT 0,

    numero_facture VARCHAR(100),          -- facultatif
    date_facture DATE,                    -- facultatif

    designation VARCHAR(255) NOT NULL,    -- une des désignations proposées, ou texte libre
    observation VARCHAR(255) NOT NULL,    -- idem

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_corporate_ar_creance CHECK (creance >= 0)
);

CREATE INDEX IF NOT EXISTS idx_corporate_ar_client_name ON corporate_ar_client (name);
CREATE INDEX IF NOT EXISTS idx_corporate_ar_client_date_facture ON corporate_ar_client (date_facture);

-- Documents joints (PDF / images) : stockés en BYTEA, plusieurs par client.
CREATE TABLE IF NOT EXISTS corporate_ar_file (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    client_code VARCHAR(50) NOT NULL REFERENCES corporate_ar_client(code) ON DELETE CASCADE,

    name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size INTEGER NOT NULL,
    data BYTEA NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_corporate_ar_file_client ON corporate_ar_file (client_code);

-- Compteur des codes CAR-xxxxxx : une seule ligne (id = 1). Il ne fait que
-- monter, donc le code d'un client supprimé n'est jamais réattribué.
CREATE TABLE IF NOT EXISTS corporate_ar_counter (
    id SMALLINT PRIMARY KEY DEFAULT 1,
    last_number INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_corporate_ar_counter_single CHECK (id = 1)
);

INSERT INTO corporate_ar_counter (id, last_number) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;
