-- ============================================================
-- Corporate AR (entreprises) : clients, factures jointes, compteur de codes.
--
-- Avant, ces données vivaient dans IndexedDB (navigateur) : elles n'étaient
-- ni partagées entre agents, ni sauvegardées. Elles sont maintenant dans
-- PostgreSQL comme le reste du projet.
--
-- NOUVELLES tables — aucune table existante n'est modifiée.
-- Idempotent : CREATE ... IF NOT EXISTS, un re-run ne perd rien.
-- ============================================================

-- Un client = une entreprise. `code` est la clé primaire : CAR-000001, CAR-000002…
-- (générée par l'API ; un import CSV peut aussi apporter son propre code).
CREATE TABLE IF NOT EXISTS corporate_ar_client (
    code VARCHAR(50) PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    creance NUMERIC(14, 2) NOT NULL DEFAULT 0,

    numero_facture VARCHAR(100),          -- facultatif
    date_facture DATE,                    -- facultatif

    designation VARCHAR(255) NOT NULL,    -- une des désignations proposées, ou texte libre
    observation VARCHAR(255) NOT NULL,    -- idem

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_corporate_ar_creance CHECK (creance >= 0)
);

CREATE INDEX IF NOT EXISTS idx_corporate_ar_client_name ON corporate_ar_client (name);
CREATE INDEX IF NOT EXISTS idx_corporate_ar_client_date_facture ON corporate_ar_client (date_facture);

-- Documents joints (PDF / images) : stockés en BYTEA, plusieurs par client.
CREATE TABLE IF NOT EXISTS corporate_ar_file (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    client_code VARCHAR(50) NOT NULL REFERENCES corporate_ar_client(code) ON DELETE CASCADE,

    name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size INTEGER NOT NULL,
    data BYTEA NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_corporate_ar_file_client ON corporate_ar_file (client_code);

-- Compteur des codes CAR-xxxxxx : une seule ligne (id = 1). Il ne fait que
-- monter, donc le code d'un client supprimé n'est jamais réattribué.
CREATE TABLE IF NOT EXISTS corporate_ar_counter (
    id SMALLINT PRIMARY KEY DEFAULT 1,
    last_number INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_corporate_ar_counter_single CHECK (id = 1)
);

INSERT INTO corporate_ar_counter (id, last_number) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;

-- updated_at suit automatiquement toute modification d'un client
-- (l'API le fait aussi elle-même ; le trigger couvre les UPDATE faits à la main dans psql).
CREATE OR REPLACE FUNCTION update_corporate_ar_client_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_corporate_ar_client_updated_at ON corporate_ar_client;

CREATE TRIGGER trg_corporate_ar_client_updated_at
BEFORE UPDATE ON corporate_ar_client
FOR EACH ROW
EXECUTE FUNCTION update_corporate_ar_client_timestamp();

-- Génère le code suivant (CAR-000001, CAR-000002…) pour une insertion faite à la main.
-- L'API a sa propre allocation (qui reste au-dessus de tout code déjà présent) : les deux
-- utilisent le même compteur, donc aucun code n'est jamais donné deux fois.
CREATE OR REPLACE FUNCTION generate_corporate_ar_code()
RETURNS VARCHAR(50)
LANGUAGE plpgsql
AS $$
DECLARE
    next_number INTEGER;
BEGIN
    UPDATE corporate_ar_counter
    SET last_number = last_number + 1
    WHERE id = 1
    RETURNING last_number INTO next_number;

    RETURN 'CAR-' || LPAD(next_number::TEXT, 6, '0');
END;
$$;
