--
-- PostgreSQL database dump
--

\restrict MM6Xb30Y9eSSAl1JcsmXdfUkicgesJPwI7p89mS2S1IqwN1dJl26hKxuZua4ZKI

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apres_gaia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia (
    n integer NOT NULL,
    codetat integer,
    codsit integer,
    cg integer,
    n_appel character varying(50),
    intitule character varying(255),
    adresse character varying(255),
    code_postal integer,
    type_de_compte integer,
    abonnement numeric(12,2),
    dus_ant numeric(12,2),
    montant_compteur numeric(12,2),
    nbre_ticket integer,
    ticket numeric(12,2),
    credit numeric(12,2),
    code_payeur integer,
    ccp bigint,
    date_vigueur_abt date,
    date_derniere_modif date,
    cod_cpt integer,
    nouvel_index integer,
    ancien_index integer,
    date_rnp date,
    dnpf date,
    repere character varying(100),
    actel character varying(255),
    n_client bigint,
    commune character varying(255),
    bat character varying(50),
    esc character varying(50),
    etage character varying(50),
    porte character varying(50),
    ccat integer,
    ndos integer,
    nvdi character varying(100),
    "motif res" character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.apres_gaia OWNER TO postgres;

--
-- Name: apres_gaia_med; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_med (
    id integer NOT NULL,
    n integer NOT NULL,
    invitation_paiement_date date,
    invitation_paiement_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    med_lettre_date date,
    med_lettre_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    engagement_date date,
    engagement_etat character varying(20) DEFAULT 'NON_ENGAGE'::character varying NOT NULL,
    cas_particulier character varying(100),
    cas_particulier_date date,
    cas_particulier_commentaire text,
    med_huissier_nom character varying(100),
    med_huissier_prenom character varying(100),
    med_huissier_date date,
    med_huissier_etat character varying(20) DEFAULT 'NON_ENVOYEE'::character varying NOT NULL,
    etat_juridique character varying(100) DEFAULT 'Procédure en cours'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_engagement_etat CHECK (((engagement_etat)::text = ANY ((ARRAY['ENGAGE'::character varying, 'NON_ENGAGE'::character varying])::text[]))),
    CONSTRAINT chk_etat_juridique CHECK (((etat_juridique)::text = ANY ((ARRAY['Procédure en cours'::character varying, 'Entreprise gagnante – première décision'::character varying, 'Client gagnant – première décision'::character varying, 'Entreprise gagnante – après recours'::character varying, 'Client gagnant – après recours'::character varying, 'Dossier clôturé'::character varying])::text[]))),
    CONSTRAINT chk_invitation_paiement_etat CHECK (((invitation_paiement_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[]))),
    CONSTRAINT chk_med_huissier_etat CHECK (((med_huissier_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[]))),
    CONSTRAINT chk_med_lettre_etat CHECK (((med_lettre_etat)::text = ANY ((ARRAY['ENVOYEE'::character varying, 'NON_ENVOYEE'::character varying])::text[])))
);


ALTER TABLE public.apres_gaia_med OWNER TO postgres;

--
-- Name: apres_gaia_med_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_med ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_med_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_n_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_n_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_rappel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_rappel (
    id integer NOT NULL,
    n integer NOT NULL,
    type character varying(100) NOT NULL,
    reference_date date,
    reference_source character varying(255),
    echeance_date date,
    mois_impayes integer,
    jours_ecoules integer,
    solde_du numeric(12,2),
    message text,
    statut character varying(20) DEFAULT 'nouveau'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at timestamp with time zone,
    resolved_at timestamp with time zone
);


ALTER TABLE public.apres_gaia_rappel OWNER TO postgres;

--
-- Name: apres_gaia_rappel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_rappel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_rappel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apres_gaia_regelement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apres_gaia_regelement (
    ref integer NOT NULL,
    n integer NOT NULL,
    somme_versement numeric(12,2),
    date_versement date,
    lieu_versement character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    statut character varying(20) DEFAULT 'en_attente'::character varying NOT NULL
);


ALTER TABLE public.apres_gaia_regelement OWNER TO postgres;

--
-- Name: apres_gaia_regelement_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apres_gaia_regelement ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apres_gaia_regelement_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avant_gaia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avant_gaia (
    ref integer NOT NULL,
    actel character varying(255),
    n_abonne character varying(50),
    intitule character varying(255),
    adresse_01 character varying(255),
    adresse_02 character varying(255),
    dnpf integer,
    type_de_compte integer,
    abonnement numeric(12,2),
    "dus Anterieur" numeric(12,2),
    montant_compteur numeric(12,2),
    nombre_ticket integer,
    montant_ticket numeric(12,2),
    credit numeric(12,2),
    code_payeur integer,
    n_ccp bigint,
    somme_ht numeric(12,2),
    ttc numeric(12,2),
    tva numeric(12,2),
    nouveau_index integer,
    avoir numeric(12,2),
    n_bimestre integer,
    annee_bimestre integer,
    n_s_t integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.avant_gaia OWNER TO postgres;

--
-- Name: avant_gaia_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avant_gaia ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avant_gaia_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avant_gaia_versement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avant_gaia_versement (
    ref integer NOT NULL,
    actel character varying(255),
    n_abonne character varying(50),
    montant_versement numeric(12,2),
    n_bimestre integer,
    annee_bimestre integer,
    n_versement integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.avant_gaia_versement OWNER TO postgres;

--
-- Name: avant_gaia_versement_ref_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avant_gaia_versement ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avant_gaia_versement_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: apres_gaia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia (n, codetat, codsit, cg, n_appel, intitule, adresse, code_postal, type_de_compte, abonnement, dus_ant, montant_compteur, nbre_ticket, ticket, credit, code_payeur, ccp, date_vigueur_abt, date_derniere_modif, cod_cpt, nouvel_index, ancien_index, date_rnp, dnpf, repere, actel, n_client, commune, bat, esc, etage, porte, ccat, ndos, nvdi, "motif res", created_at, updated_at) FROM stdin;
1	1	10	1	APP001	SARL ALPHA	12 Rue des Oliviers	16000	1	12500.00	1500.00	11000.00	2	500.00	300.00	1	123456789	2026-01-01	2026-02-15	1001	2500	2200	2026-02-01	2026-02-10	REP001	ACTEL ALGER	100001	Alger	B1	E2	3	12	1	5001	NVDI001	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
2	1	10	1	APP002	ETS BETA	25 Rue Didouche Mourad	16000	1	9800.00	1200.00	8600.00	1	250.00	150.00	2	234567890	2026-01-01	2026-02-20	1002	1800	1600	2026-02-05	2026-02-12	REP002	ACTEL ALGER	100002	Alger	B2	E1	2	8	1	5002	NVDI002	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
3	2	20	2	APP003	SARL GAMMA	8 Rue Larbi Ben M'hidi	19000	2	15750.00	2300.00	13450.00	3	750.00	400.00	1	345678901	2026-01-15	2026-02-18	1003	3200	2900	2026-02-10	2026-02-15	REP003	ACTEL SETIF	100003	Setif	C1	E3	4	15	2	5003	NVDI003	Modification	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
4	1	10	1	APP004	ETS DELTA	45 Rue de la Liberté	16000	1	7200.00	800.00	6400.00	1	200.00	100.00	2	456789012	2026-01-01	2026-02-22	1004	1400	1200	2026-02-12	2026-02-18	REP004	ACTEL ALGER	100004	Alger	D1	E2	1	4	1	5004	NVDI004	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
5	2	20	2	APP005	SARL EPSILON	17 Rue de Constantine	25000	2	11200.00	1800.00	9400.00	2	450.00	250.00	1	567890123	2026-01-10	2026-02-25	1005	2100	1900	2026-02-15	2026-02-20	REP005	ACTEL CONSTANTINE	100005	Constantine	E1	E1	3	10	2	5005	NVDI005	Normal	2026-09-28 00:08:59.59522+00	2026-09-28 00:08:59.59522+00
6	1	10	1	APP006	SARL TEST API	15 Rue des Freres Bouadou	16000	1	10500.50	1200.00	9300.50	2	450.00	200.00	1	678901234	2026-09-01	2026-09-28	1006	3500	3200	2026-09-15	2026-09-20	REP006	ACTEL ALGER	100006	Alger	F1	E2	4	16	1	5006	NVDI006	Normal	2026-09-28 00:27:32.514166+00	2026-09-28 00:27:32.514166+00
\.


--
-- Data for Name: apres_gaia_med; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia_med (id, n, invitation_paiement_date, invitation_paiement_etat, med_lettre_date, med_lettre_etat, engagement_date, engagement_etat, cas_particulier, cas_particulier_date, cas_particulier_commentaire, med_huissier_nom, med_huissier_prenom, med_huissier_date, med_huissier_etat, etat_juridique, created_at, updated_at) FROM stdin;
1	1	2026-01-15	ENVOYEE	2026-02-10	ENVOYEE	2026-02-20	ENGAGE	\N	\N	\N	\N	\N	\N	NON_ENVOYEE	Procédure en cours	2026-09-29 00:22:05.688827+00	2026-09-29 00:22:05.688827+00
2	2	2026-01-20	ENVOYEE	2026-02-15	ENVOYEE	2026-02-20	ENGAGE	Décès	2026-03-01	Dossier à traiter avec les ayants droit.	Benali	Ahmed	2026-03-15	ENVOYEE	Procédure en cours	2026-09-29 00:22:05.688827+00	2026-09-29 00:22:05.688827+00
4	4	2026-02-01	ENVOYEE	2026-02-20	ENVOYEE	2026-03-01	ENGAGE	Contestation	2026-03-10	Le client conteste le montant réclamé.	Kaci	Mohamed	2026-03-20	ENVOYEE	Entreprise gagnante – première décision	2026-09-29 00:22:05.688827+00	2026-09-29 00:22:05.688827+00
3	3	2026-01-25	ENVOYEE	2026-02-10	ENVOYEE	2026-09-29	ENGAGE	Insolvabilité	2026-03-05	Situation financière particulière du client.	kali	meriem	2026-09-29	ENVOYEE	Procédure en cours	2026-09-29 00:22:05.688827+00	2026-09-29 10:46:51.821634+00
5	5	2026-09-29	ENVOYEE	2026-09-29	ENVOYEE	2026-09-29	ENGAGE	\N	\N	\N	\N	\N	\N	NON_ENVOYEE	Procédure en cours	2026-09-29 10:51:49.450705+00	2026-09-29 10:51:52.995832+00
\.


--
-- Data for Name: apres_gaia_rappel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia_rappel (id, n, type, reference_date, reference_source, echeance_date, mois_impayes, jours_ecoules, solde_du, message, statut, created_at, read_at, resolved_at) FROM stdin;
1	4	versement_mensuel	2026-03-01	engagement	2026-09-27	7	212	11900.00	Rappel : le client n° 4 (ETS DELTA) est engagé mais n'a effectué aucun versement depuis son engagement du 01/03/2026 — 212 jours écoulés (7 mois). Solde dû : 11900.00.	nouveau	2026-09-29 10:42:51.254709+00	\N	\N
\.


--
-- Data for Name: apres_gaia_regelement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apres_gaia_regelement (ref, n, somme_versement, date_versement, lieu_versement, created_at, updated_at, statut) FROM stdin;
1	1	3000.00	2026-02-05	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
2	1	2500.00	2026-02-20	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
3	1	1500.00	2026-03-10	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	en_attente
4	2	4000.00	2026-02-10	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
5	2	2000.00	2026-03-05	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	en_attente
6	3	5000.00	2026-02-15	Bureau ACTEL Setif	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
7	3	3000.00	2026-03-12	Bureau ACTEL Setif	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
8	4	2500.00	2026-02-18	Bureau ACTEL Alger	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
9	5	3500.00	2026-02-22	Bureau ACTEL Constantine	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	en_attente
10	5	2000.00	2026-03-15	Bureau ACTEL Constantine	2026-09-28 00:47:03.375908+00	2026-09-28 00:47:03.375908+00	valide
11	2	3500.00	2026-09-28	Bureau ACTEL Constantine	2026-09-28 00:48:51.105525+00	2026-09-28 00:48:51.105525+00	valide
12	1	2000.00	\N	alger	2026-09-28 09:57:47.661986+00	2026-09-28 09:57:47.661986+00	valide
13	3	3000.00	\N	alger	2026-09-28 12:05:48.704374+00	2026-09-28 12:05:48.704374+00	valide
14	1	3000.00	\N	kouba	2026-09-28 12:19:17.279334+00	2026-09-28 12:19:17.279334+00	refuse
15	1	4000.00	\N	koubq	2026-09-28 12:20:01.272027+00	2026-09-28 12:20:01.272027+00	valide
16	3	20500.00	\N	kouba	2026-09-29 10:47:11.80038+00	2026-09-29 10:47:11.80038+00	valide
\.


--
-- Data for Name: avant_gaia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.avant_gaia (ref, actel, n_abonne, intitule, adresse_01, adresse_02, dnpf, type_de_compte, abonnement, "dus Anterieur", montant_compteur, nombre_ticket, montant_ticket, credit, code_payeur, n_ccp, somme_ht, ttc, tva, nouveau_index, avoir, n_bimestre, annee_bimestre, n_s_t, created_at, updated_at) FROM stdin;
1	ACTEL ALGER	100001	SARL ALPHA	12 Rue des Oliviers	Alger Centre	1	1	12500.00	1500.00	11000.00	2	500.00	300.00	1	123456789	10000.00	11900.00	1900.00	2500	0.00	1	2026	1001	2026-09-28 00:10:34.285008+00	2026-09-28 00:10:34.285008+00
2	ACTEL ALGER	100002	ETS BETA	25 Rue Didouche Mourad	Alger Centre	1	1	9800.00	1200.00	8600.00	1	250.00	150.00	2	234567890	8000.00	9440.00	1440.00	1800	0.00	1	2026	1002	2026-09-28 00:10:34.285008+00	2026-09-28 00:10:34.285008+00
3	ACTEL SETIF	100003	SARL GAMMA	8 Rue Larbi Ben M'hidi	Setif Centre	2	2	15750.00	2300.00	13450.00	3	750.00	400.00	1	345678901	13000.00	15340.00	2340.00	3200	0.00	1	2026	1003	2026-09-28 00:10:34.285008+00	2026-09-28 00:10:34.285008+00
\.


--
-- Data for Name: avant_gaia_versement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.avant_gaia_versement (ref, actel, n_abonne, montant_versement, n_bimestre, annee_bimestre, n_versement, created_at, updated_at) FROM stdin;
1	ACTEL ALGER	100001	3000.00	1	2026	1	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
2	ACTEL ALGER	100001	2500.00	1	2026	2	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
3	ACTEL ALGER	100002	4000.00	1	2026	1	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
4	ACTEL SETIF	100003	5000.00	1	2026	1	2026-09-28 00:11:05.299324+00	2026-09-28 00:11:05.299324+00
\.


--
-- Name: apres_gaia_med_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_med_id_seq', 5, true);


--
-- Name: apres_gaia_n_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_n_seq', 6, true);


--
-- Name: apres_gaia_rappel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_rappel_id_seq', 1, true);


--
-- Name: apres_gaia_regelement_ref_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apres_gaia_regelement_ref_seq', 16, true);


--
-- Name: avant_gaia_ref_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.avant_gaia_ref_seq', 3, true);


--
-- Name: avant_gaia_versement_ref_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.avant_gaia_versement_ref_seq', 4, true);


--
-- Name: apres_gaia_med apres_gaia_med_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_med
    ADD CONSTRAINT apres_gaia_med_pkey PRIMARY KEY (id);


--
-- Name: apres_gaia apres_gaia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia
    ADD CONSTRAINT apres_gaia_pkey PRIMARY KEY (n);


--
-- Name: apres_gaia_rappel apres_gaia_rappel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_rappel
    ADD CONSTRAINT apres_gaia_rappel_pkey PRIMARY KEY (id);


--
-- Name: apres_gaia_regelement apres_gaia_regelement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_regelement
    ADD CONSTRAINT apres_gaia_regelement_pkey PRIMARY KEY (ref);


--
-- Name: avant_gaia avant_gaia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avant_gaia
    ADD CONSTRAINT avant_gaia_pkey PRIMARY KEY (ref);


--
-- Name: avant_gaia_versement avant_gaia_versement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avant_gaia_versement
    ADD CONSTRAINT avant_gaia_versement_pkey PRIMARY KEY (ref);


--
-- Name: apres_gaia_rappel apres_gaia_rappel_n_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_rappel
    ADD CONSTRAINT apres_gaia_rappel_n_fkey FOREIGN KEY (n) REFERENCES public.apres_gaia(n) ON DELETE CASCADE;


--
-- Name: apres_gaia_med fk_apres_gaia_med_n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_med
    ADD CONSTRAINT fk_apres_gaia_med_n FOREIGN KEY (n) REFERENCES public.apres_gaia(n) ON DELETE CASCADE;


--
-- Name: apres_gaia_regelement fk_regelement_apres_gaia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apres_gaia_regelement
    ADD CONSTRAINT fk_regelement_apres_gaia FOREIGN KEY (n) REFERENCES public.apres_gaia(n);


--
-- PostgreSQL database dump complete
--

\unrestrict MM6Xb30Y9eSSAl1JcsmXdfUkicgesJPwI7p89mS2S1IqwN1dJl26hKxuZua4ZKI

