-- ============================================================
-- TABLE 1: avant_gaia
-- ============================================================

CREATE TABLE IF NOT EXISTS avant_gaia (
    ref INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    actel VARCHAR(255),
    n_abonne VARCHAR(50),
    intitule VARCHAR(255),
    adresse_01 VARCHAR(255),
    adresse_02 VARCHAR(255),

    dnpf INTEGER,
    type_de_compte INTEGER,
    abonnement NUMERIC(12, 2),

    "dus Anterieur" NUMERIC(12, 2),
    montant_compteur NUMERIC(12, 2),

    nombre_ticket INTEGER,
    montant_ticket NUMERIC(12, 2),

    credit NUMERIC(12, 2),
    code_payeur INTEGER,

    n_ccp BIGINT,

    somme_ht NUMERIC(12, 2),
    ttc NUMERIC(12, 2),
    tva NUMERIC(12, 2),

    nouveau_index INTEGER,
    avoir NUMERIC(12, 2),

    n_bimestre INTEGER,
    annee_bimestre INTEGER,
    n_s_t INTEGER,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- TABLE 2: avant_gaia_versement
-- ============================================================

CREATE TABLE IF NOT EXISTS avant_gaia_versement (
    ref INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    actel VARCHAR(255),
    n_abonne VARCHAR(50),

    montant_versement NUMERIC(12, 2),

    n_bimestre INTEGER,
    annee_bimestre INTEGER,
    n_versement INTEGER,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
