-- ============================================================
-- TABLE 5: apres_gaia
-- Your real DDL, applied as-is.
-- ============================================================

CREATE TABLE IF NOT EXISTS apres_gaia (
    n INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codetat INTEGER,
    codsit INTEGER,
    cg INTEGER,

    n_appel VARCHAR(50),

    intitule VARCHAR(255),
    adresse VARCHAR(255),

    code_postal INTEGER,

    type_de_compte INTEGER,

    abonnement NUMERIC(12, 2),
    dus_ant NUMERIC(12, 2),
    montant_compteur NUMERIC(12, 2),

    nbre_ticket INTEGER,
    ticket NUMERIC(12, 2),
    credit NUMERIC(12, 2),

    code_payeur INTEGER,

    ccp BIGINT,

    date_vigueur_abt DATE,
    date_derniere_modif DATE,

    cod_cpt INTEGER,

    nouvel_index INTEGER,
    ancien_index INTEGER,

    date_rnp DATE,
    dnpf DATE,

    repere VARCHAR(100),
    actel VARCHAR(255),

    n_client BIGINT,

    commune VARCHAR(255),
    bat VARCHAR(50),
    esc VARCHAR(50),
    etage VARCHAR(50),
    porte VARCHAR(50),

    ccat INTEGER,
    ndos INTEGER,

    nvdi VARCHAR(100),

    "motif res" VARCHAR(255),

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
