-- ============================================================
-- TABLE 7: apres_gaia_med
-- Mises en demeure (MED) + engagement (avec « cas particulier » et
-- commentaire) + état juridique d'un client Après Gaïa.
-- Ton DDL, appliqué tel quel (idem contraintes CHECK) — y compris les
-- 3 colonnes cas_particulier* désormais directement dans le CREATE.
--
-- Seule différence : CREATE TABLE IF NOT EXISTS au lieu de
-- DROP TABLE IF EXISTS + CREATE, pour rester idempotent comme les
-- autres migrations (un re-run ne supprime jamais de données).
--
-- Repartir de zéro en dev (⚠ efface tout le suivi MED) :
--     DROP TABLE IF EXISTS apres_gaia_med;
-- puis relance ce fichier.
--
-- Base déjà créée AVANT l'ajout des colonnes cas_particulier* ?
-- Rien à faire : sql/007 les ajoute (ADD COLUMN IF NOT EXISTS).
-- ============================================================

CREATE TABLE IF NOT EXISTS apres_gaia_med (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    n INTEGER NOT NULL,

    -- Invitation de paiement
    invitation_paiement_date DATE,
    invitation_paiement_etat VARCHAR(20) NOT NULL DEFAULT 'NON_ENVOYEE',

    -- Mise en demeure par lettre
    med_lettre_date DATE,
    med_lettre_etat VARCHAR(20) NOT NULL DEFAULT 'NON_ENVOYEE',

    -- Engagement du client
    engagement_date DATE,
    engagement_etat VARCHAR(20) NOT NULL DEFAULT 'NON_ENGAGE',

    -- Cas particulier lié au client / engagement
    cas_particulier VARCHAR(100),
    cas_particulier_date DATE,
    cas_particulier_commentaire TEXT,

    -- Mise en demeure par huissier
    med_huissier_nom VARCHAR(100),
    med_huissier_prenom VARCHAR(100),
    med_huissier_date DATE,
    med_huissier_etat VARCHAR(20) NOT NULL DEFAULT 'NON_ENVOYEE',

    -- État juridique
    etat_juridique VARCHAR(100) NOT NULL
        DEFAULT 'Procédure en cours',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_apres_gaia_med_n
        FOREIGN KEY (n)
        REFERENCES apres_gaia(n)
        ON DELETE CASCADE,

    CONSTRAINT chk_invitation_paiement_etat
        CHECK (
            invitation_paiement_etat IN (
                'ENVOYEE',
                'NON_ENVOYEE'
            )
        ),

    CONSTRAINT chk_med_lettre_etat
        CHECK (
            med_lettre_etat IN (
                'ENVOYEE',
                'NON_ENVOYEE'
            )
        ),

    CONSTRAINT chk_engagement_etat
        CHECK (
            engagement_etat IN (
                'ENGAGE',
                'NON_ENGAGE'
            )
        ),

    CONSTRAINT chk_med_huissier_etat
        CHECK (
            med_huissier_etat IN (
                'ENVOYEE',
                'NON_ENVOYEE'
            )
        ),

    CONSTRAINT chk_etat_juridique
        CHECK (
            etat_juridique IN (
                'Procédure en cours',
                'Entreprise gagnante – première décision',
                'Client gagnant – première décision',
                'Entreprise gagnante – après recours',
                'Client gagnant – après recours',
                'Dossier clôturé'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_apres_gaia_med_n ON apres_gaia_med (n);
